spring:
  datasource:
    url: jdbc:mysql://192.168.99.156:3306/movie?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: walle
    filters: wall,mergeStat
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 配置 mybatis

jpa:
    show-sql: true
#
#mybatis:
#  type-aliases-package: com.yixuan.pojo
#  mapper-locations: classpath:mybatis/mapper/user/*.xml



