spring:
  datasource:
    url: jdbc:mysql://192.168.99.156:33060/movie?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: movie
    password: movie
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
  redis:
    host: 192.168.99.156
    port: 6379
    database: 0
  cache:
    type: redis # 设置使用 redis 作为缓存 (此行可以不配置)
    redis:
      time-to-live: 60s

server:
    port: 8081

filePath: E:/迅雷下载/



#mybatis:
#  type-aliases-package: com.yixuan.pojo
#  mapper-locations: classpath:mybatis/mapper/user/*.xml



