package com.free.video.model;

import lombok.Data;
import lombok.ToString;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;


@Data
@Entity
@ToString
@Table(name="system_config")
public class SystemConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.id
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Id    //主键id
    @GenericGenerator(name = "m-uuid", strategy = "uuid")
    @GeneratedValue(generator = "m-uuid")
    @Column(name = "id")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.name
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "sys_code")
    private String sysCode;


    @Column(name = "sys_value")
    private String sysValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.update_time
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "update_time")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.create_time
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "create_time")
    private Date createTime;

}