package com.free.video.model;

import lombok.Data;

import javax.persistence.*;
import java.util.Date;


@Data
@Entity
@Table(name="video_tag")
public class VideoTag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_tag.id
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Id    //主键id
    @GeneratedValue(strategy = GenerationType.IDENTITY)//主键生成策略
    @Column(name = "id")//数据库字段名
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_tag.name
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "name")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_tag.tag_type
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "tagType")
    private String tagType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_tag.create_time
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "createTime")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_tag.update_time
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "updateTime")
    private Date updateTime;
}