package com.free.video.model;

import lombok.Data;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.*;
import java.util.Date;


@Data
@Entity
@Table(name="video_file")
public class VideoFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.id
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Id    //主键id
    @GenericGenerator(name = "m-uuid", strategy = "uuid")
    @GeneratedValue(generator = "m-uuid")
    @Column(name = "id")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.name
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "name")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.file_path
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "filePath")
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.file_size
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "fileSize")
    private String fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.update_time
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "updateTime")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.create_time
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "createTime")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_file.is_delete
     *
     * @mbggenerated Tue Aug 04 23:32:40 CST 2020
     */
    @Column(name = "isDelete")
    private String isDelete;
}